spring:
  application:
    name: spring-boot-basics
stripe:
  apiUrl: https://api.stripe.com
  timeout: 1000
  enabled: true
  supported-currencies: USD, EUR, GBP
payment-gateway: stripe
server-settings:
  host: localhost
  port: 3000